2018-04-16T00:05:56.3444355+01:00 0HLD34LOR8L2N:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T00:05:57.1654825+01:00 0HLD34LOR8L2N:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T00:06:27.8502375+01:00 0HLD34LOR8L2N:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 30736.7248ms (afa2e885)
2018-04-16T00:06:28.4112696+01:00 0HLD34LOR8L2N:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Xml.XmlException: The ' ' character, hexadecimal value 0x20, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at Tinix.Context.FileBlogService.LoadFromDisk() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 246
   at Tinix.Context.FileBlogService.GetCachedPosts() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 192
   at Tinix.Context.FileBlogService.GetPosts(Int32 count, Int32 skip) in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 175
   at Tinix.Controllers.HomeController.<Index>d__5.MoveNext() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix\Controllers\HomeController.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-16T00:06:28.6202816+01:00 0HLD34LOR8L2N:00000001 [INF] Request finished in 32319.3243ms 500 text/html; charset=utf-8 (791a596a)
2018-04-16T22:16:07.5437588+01:00 0HLD3RT2A80PS:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:16:11.8110028+01:00 0HLD3RT2A80PS:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:16:49.6181653+01:00 0HLD3RT2A80PS:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 37966.6503ms (afa2e885)
2018-04-16T22:16:50.6662252+01:00 0HLD3RT2A80PS:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Xml.XmlException: The ' ' character, hexadecimal value 0x20, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at Tinix.Context.FileBlogService.LoadFromDisk() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 246
   at Tinix.Context.FileBlogService.GetCachedPosts() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 192
   at Tinix.Context.FileBlogService.GetPosts(Int32 count, Int32 skip) in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 175
   at Tinix.Controllers.HomeController.<Index>d__5.MoveNext() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix\Controllers\HomeController.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-16T22:16:50.9272402+01:00 0HLD3RT2A80PS:00000001 [INF] Request finished in 43430.6932ms 500 text/html; charset=utf-8 (791a596a)
2018-04-16T22:18:48.0419387+01:00 0HLD3RUIAVG6G:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:18:48.3559567+01:00 0HLD3RUIAVG6G:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:19:05.8479572+01:00 0HLD3RUIAVG6G:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 17528.1297ms (afa2e885)
2018-04-16T22:19:05.9629638+01:00 0HLD3RUIAVG6G:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Xml.XmlException: The ' ' character, hexadecimal value 0x20, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at Tinix.Context.FileBlogService.LoadFromDisk() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 246
   at Tinix.Context.FileBlogService.GetCachedPosts() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 192
   at Tinix.Context.FileBlogService.GetPosts(Int32 count, Int32 skip) in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 175
   at Tinix.Controllers.HomeController.<Index>d__5.MoveNext() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix\Controllers\HomeController.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-16T22:19:06.0999716+01:00 0HLD3RUIAVG6G:00000001 [INF] Request finished in 18068.3086ms 500 text/html; charset=utf-8 (791a596a)
2018-04-16T22:20:10.7816712+01:00 0HLD3RVARH9VV:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:20:11.1156903+01:00 0HLD3RVARH9VV:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:20:17.4870547+01:00 0HLD3RVARH9VV:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 6405.3753ms (afa2e885)
2018-04-16T22:20:17.6120619+01:00 0HLD3RVARH9VV:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Xml.XmlException: The ' ' character, hexadecimal value 0x20, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at Tinix.Context.FileBlogService.LoadFromDisk() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 246
   at Tinix.Context.FileBlogService.GetCachedPosts() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 192
   at Tinix.Context.FileBlogService.GetPosts(Int32 count, Int32 skip) in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 175
   at Tinix.Controllers.HomeController.<Index>d__5.MoveNext() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix\Controllers\HomeController.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-16T22:20:17.7680708+01:00 0HLD3RVARH9VV:00000001 [INF] Request finished in 6995.536ms 500 text/html; charset=utf-8 (791a596a)
2018-04-16T22:20:57.3093324+01:00 0HLD3RVONO9H1:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:20:57.6413514+01:00 0HLD3RVONO9H1:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:21:04.7507580+01:00 0HLD3RVONO9H1:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 7145.2876ms (afa2e885)
2018-04-16T22:21:04.8747651+01:00 0HLD3RVONO9H1:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Xml.XmlException: The ' ' character, hexadecimal value 0x20, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at Tinix.Context.FileBlogService.LoadFromDisk() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 246
   at Tinix.Context.FileBlogService.GetCachedPosts() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 192
   at Tinix.Context.FileBlogService.GetPosts(Int32 count, Int32 skip) in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 175
   at Tinix.Controllers.HomeController.<Index>d__5.MoveNext() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix\Controllers\HomeController.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-16T22:21:05.0527753+01:00 0HLD3RVONO9H1:00000001 [INF] Request finished in 7749.8002ms 500 text/html; charset=utf-8 (791a596a)
2018-04-16T22:21:58.3948263+01:00 0HLD3S0AVHFCL:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:21:58.7808484+01:00 0HLD3S0AVHFCL:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:21:58.8748538+01:00 0HLD3S0AVHFCL:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 177.7621ms (afa2e885)
2018-04-16T22:21:58.9938606+01:00 0HLD3S0AVHFCL:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Xml.XmlException: The ' ' character, hexadecimal value 0x20, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at Tinix.Context.FileBlogService.LoadFromDisk() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 246
   at Tinix.Context.FileBlogService.GetCachedPosts() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 192
   at Tinix.Context.FileBlogService.GetPosts(Int32 count, Int32 skip) in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 175
   at Tinix.Controllers.HomeController.<Index>d__5.MoveNext() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix\Controllers\HomeController.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-16T22:21:59.1168676+01:00 0HLD3S0AVHFCL:00000001 [INF] Request finished in 732.988ms 500 text/html; charset=utf-8 (791a596a)
2018-04-16T22:53:12.5560222+01:00 0HLD3SHPJVE7I:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:53:12.8930415+01:00 0HLD3SHPJVE7I:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:53:41.0126498+01:00 0HLD3SHPJVE7I:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-16T22:53:42.9007578+01:00 0HLD3SHPJVE7I:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 30036.3487ms (afa2e885)
2018-04-16T22:53:43.0127642+01:00 0HLD3SHPJVE7I:00000001 [INF] Request finished in 30437.7957ms 200 text/html; charset=utf-8 (791a596a)
2018-04-16T22:53:43.0227648+01:00 0HLD3SHPJVE7J:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/css/bootstrap.min.css   (ca22a1cb)
2018-04-16T22:53:43.0377656+01:00 0HLD3SHPJVE7L:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/css/site.css   (ca22a1cb)
2018-04-16T22:53:43.0627671+01:00 0HLD3SHPJVE7K:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/js/jquery.js   (ca22a1cb)
2018-04-16T22:53:43.0637671+01:00 0HLD3SHPJVE7J:00000001 [INF] The file "/css/bootstrap.min.css" was not modified (f1f8d725)
2018-04-16T22:53:43.0667673+01:00 0HLD3SHPJVE7L:00000001 [INF] The file "/css/site.css" was not modified (f1f8d725)
2018-04-16T22:53:43.0697675+01:00 0HLD3SHPJVE7K:00000001 [INF] The file "/js/jquery.js" was not modified (f1f8d725)
2018-04-16T22:53:43.0857684+01:00 0HLD3SHPJVE7K:00000001 [INF] Request finished in 56.5458ms 304 application/javascript (791a596a)
2018-04-16T22:53:43.1127699+01:00 0HLD3SHPJVE7L:00000001 [INF] Request finished in 60.7298ms 304 text/css (791a596a)
2018-04-16T22:53:43.1177702+01:00 0HLD3SHPJVE7J:00000001 [INF] Request finished in 60.7317ms 304 text/css (791a596a)
2018-04-16T22:53:43.2507778+01:00 0HLD3SHPJVE7K:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5000/js/popper.min.js   (ca22a1cb)
2018-04-16T22:53:43.2537780+01:00 0HLD3SHPJVE7J:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5000/js/bootstrap.min.js   (ca22a1cb)
2018-04-16T22:53:43.2777794+01:00 0HLD3SHPJVE7K:00000002 [INF] The file "/js/popper.min.js" was not modified (f1f8d725)
2018-04-16T22:53:43.2857798+01:00 0HLD3SHPJVE7J:00000002 [INF] The file "/js/bootstrap.min.js" was not modified (f1f8d725)
2018-04-16T22:53:43.2877799+01:00 0HLD3SHPJVE7K:00000002 [INF] Request finished in 41.3421ms 304 application/javascript (791a596a)
2018-04-16T22:53:43.2907801+01:00 0HLD3SHPJVE7J:00000002 [INF] Request finished in 43.8188ms 304 application/javascript (791a596a)
2018-04-16T22:54:09.9993078+01:00 0HLD3SIAEM93O:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:54:10.3303267+01:00 0HLD3SIAEM93O:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:54:23.2580661+01:00 0HLD3SIAEM93O:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-16T22:54:24.8501572+01:00 0HLD3SIAEM93O:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 14545.6561ms (afa2e885)
2018-04-16T22:54:24.8841591+01:00 0HLD3SIAEM93O:00000001 [INF] Request finished in 14871.7885ms 200 text/html; charset=utf-8 (791a596a)
2018-04-16T22:55:58.4335098+01:00 0HLD3SJAVBE7L:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:55:58.7415275+01:00 0HLD3SJAVBE7L:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:56:05.7619290+01:00 0HLD3SJAVBE7L:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-16T22:56:07.9060516+01:00 0HLD3SJAVBE7L:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 9115.1373ms (afa2e885)
2018-04-16T22:56:07.9230526+01:00 0HLD3SJAVBE7L:00000001 [INF] Request finished in 9493.0983ms 200 text/html; charset=utf-8 (791a596a)
2018-04-16T22:57:03.2102149+01:00 0HLD3SJU6HAC5:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:57:03.5332333+01:00 0HLD3SJU6HAC5:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:57:16.9750022+01:00 0HLD3SJU6HAC5:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-16T22:57:18.6130959+01:00 0HLD3SJU6HAC5:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 15068.7924ms (afa2e885)
2018-04-16T22:57:18.6450977+01:00 0HLD3SJU6HAC5:00000001 [INF] Request finished in 15435.3899ms 200 text/html; charset=utf-8 (791a596a)
2018-04-16T22:59:17.1228742+01:00 0HLD3SL64D80M:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T22:59:17.4468928+01:00 0HLD3SL64D80M:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T22:59:43.0343563+01:00 0HLD3SL64D80M:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-16T22:59:44.7364536+01:00 0HLD3SL64D80M:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 27266.4106ms (afa2e885)
2018-04-16T22:59:44.7594549+01:00 0HLD3SL64D80M:00000001 [INF] Request finished in 27636.018ms 200 text/html; charset=utf-8 (791a596a)
2018-04-16T23:07:30.7101058+01:00 0HLD3SPP7LASK:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T23:07:31.0641260+01:00 0HLD3SPP7LASK:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T23:09:13.5399873+01:00 0HLD3SPP7LASK:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 102505.9746ms (afa2e885)
2018-04-16T23:09:13.6439933+01:00 0HLD3SPP7LASK:00000001 [ERR] An unhandled exception has occurred while executing the request (cf926119)
System.Xml.XmlException: The ' ' character, hexadecimal value 0x20, cannot be included in a name.
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.XmlConvert.VerifyNCName(String name)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName, Int32 index, Int32 count)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at System.Xml.Linq.XName.op_Implicit(String expandedName)
   at Tinix.Context.FileBlogService.LoadFromDisk() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 246
   at Tinix.Context.FileBlogService.GetCachedPosts() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 192
   at Tinix.Context.FileBlogService.GetPosts(Int32 count, Int32 skip) in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix.Context\FileBlogService.cs:line 175
   at Tinix.Controllers.HomeController.<Index>d__5.MoveNext() in C:\Users\ozan\Desktop\projects\Tinix\src\Tinix\Controllers\HomeController.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-04-16T23:09:13.7870015+01:00 0HLD3SPP7LASK:00000001 [INF] Request finished in 103083.0402ms 500 text/html; charset=utf-8 (791a596a)
2018-04-16T23:21:36.6904931+01:00 0HLD3T1L9QQDT:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T23:21:37.4295354+01:00 0HLD3T1L9QQDT:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T23:22:15.2887008+01:00 0HLD3T1L9QQDT:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-16T23:22:17.0598021+01:00 0HLD3T1L9QQDT:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 39663.799ms (afa2e885)
2018-04-16T23:22:17.1318062+01:00 0HLD3T1L9QQDT:00000001 [INF] Request finished in 40391.2203ms 200 text/html; charset=utf-8 (791a596a)
2018-04-16T23:25:39.9104045+01:00 0HLD3T3TU558N:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T23:25:40.2694250+01:00 0HLD3T3TU558N:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T23:26:19.3426599+01:00 0HLD3T3TU558N:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-16T23:26:20.9427514+01:00 0HLD3T3TU558N:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 40707.8096ms (afa2e885)
2018-04-16T23:26:20.9837538+01:00 0HLD3T3TU558O:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/css/bootstrap.min.css   (ca22a1cb)
2018-04-16T23:26:20.9897541+01:00 0HLD3T3TU558P:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/css/site.css   (ca22a1cb)
2018-04-16T23:26:21.0027548+01:00 0HLD3T3TU558P:00000001 [INF] Sending file. Request path: '"/css/site.css"'. Physical path: '"C:\Users\ozan\desktop\projects\tinix\src\Tinix\wwwroot\css\site.css"' (27b0a520)
2018-04-16T23:26:21.0057550+01:00 0HLD3T3TU558O:00000001 [INF] Sending file. Request path: '"/css/bootstrap.min.css"'. Physical path: '"C:\Users\ozan\desktop\projects\tinix\src\Tinix\wwwroot\css\bootstrap.min.css"' (27b0a520)
2018-04-16T23:26:21.0177557+01:00 0HLD3T3TU558Q:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/js/jquery.js   (ca22a1cb)
2018-04-16T23:26:21.0567579+01:00 0HLD3T3TU558Q:00000001 [INF] Sending file. Request path: '"/js/jquery.js"'. Physical path: '"C:\Users\ozan\desktop\projects\tinix\src\Tinix\wwwroot\js\jquery.js"' (27b0a520)
2018-04-16T23:26:21.0657584+01:00 0HLD3T3TU558P:00000001 [INF] Request finished in 77.3298ms 200 text/css (791a596a)
2018-04-16T23:26:21.0697587+01:00 0HLD3T3TU558N:00000001 [INF] Request finished in 41104.4465ms 200 text/html; charset=utf-8 (791a596a)
2018-04-16T23:26:21.0917599+01:00 0HLD3T3TU558O:00000001 [INF] Request finished in 104.9321ms 200 text/css (791a596a)
2018-04-16T23:26:21.0957602+01:00 0HLD3T3TU558P:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5000/js/bootstrap.min.js   (ca22a1cb)
2018-04-16T23:26:21.0987603+01:00 0HLD3T3TU558O:00000002 [INF] Request starting HTTP/1.1 GET http://localhost:5000/js/popper.min.js   (ca22a1cb)
2018-04-16T23:26:21.1037606+01:00 0HLD3T3TU558P:00000002 [INF] Sending file. Request path: '"/js/bootstrap.min.js"'. Physical path: '"C:\Users\ozan\desktop\projects\tinix\src\Tinix\wwwroot\js\bootstrap.min.js"' (27b0a520)
2018-04-16T23:26:21.1047607+01:00 0HLD3T3TU558O:00000002 [INF] Sending file. Request path: '"/js/popper.min.js"'. Physical path: '"C:\Users\ozan\desktop\projects\tinix\src\Tinix\wwwroot\js\popper.min.js"' (27b0a520)
2018-04-16T23:26:21.1277620+01:00 0HLD3T3TU558O:00000002 [INF] Request finished in 24.3727ms 200 application/javascript (791a596a)
2018-04-16T23:26:21.1667642+01:00 0HLD3T3TU558Q:00000001 [INF] Request finished in 135.6591ms 200 application/javascript (791a596a)
2018-04-16T23:26:21.1727646+01:00 0HLD3T3TU558P:00000002 [INF] Request finished in 62.5077ms 200 application/javascript (791a596a)
2018-04-16T23:27:42.7324295+01:00 0HLD3T52BU4UL:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T23:27:43.0534479+01:00 0HLD3T52BU4UL:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
2018-04-16T23:28:16.6493694+01:00 0HLD3T52BU4UL:00000001 [INF] Executing ViewResult, running view at path "/Views/Home/Index.cshtml". (9707eebe)
2018-04-16T23:28:18.4254710+01:00 0HLD3T52BU4UL:00000001 [INF] Executed action "Tinix.Controllers.HomeController.Index (Tinix)" in 35390.5915ms (afa2e885)
2018-04-16T23:28:18.4994753+01:00 0HLD3T52BU4UL:00000001 [INF] Request finished in 35731.0319ms 200 text/html; charset=utf-8 (791a596a)
2018-04-16T23:30:20.2314379+01:00 0HLD3T6HEE5HL:00000001 [INF] Request starting HTTP/1.1 GET http://localhost:5000/   (ca22a1cb)
2018-04-16T23:30:20.5784578+01:00 0HLD3T6HEE5HL:00000001 [INF] Executing action method "Tinix.Controllers.HomeController.Index (Tinix)" with arguments ([""]) - ModelState is Valid (ba7f4ac2)
